"""Proposed production architecture pages, separate from local execution details."""
from html import escape as e
from portfolio import DEFINITIONS

FLOWS = {
 "report": {
  "intent":"Support asks why Northstar's September sales report differs from the spreadsheet.",
  "queries":[("Git repository","Find the report entry point, date/type filters, return normalization and existing tests at a fixed commit."),("Jira","Read the support request, linked incidents and ATLAS rollout decision. Check the scope of completed work."),("Confluence","Retrieve the effective September sales definition and both approved ATLAS format contracts. Match each row's schema version.")],
  "join":[("Repository: every RETURN is negated","ATLAS v1 contract: preserve the original sign","The code reverses the meaning of two v1 rows; the business contract supplies the missing requirement."),("Customer spreadsheet: $1,150","Approved definitions + five original transaction rows","Recalculate independently: $1,250. Neither starting total is authoritative."),("Jira rollout record","Both format contracts","A completed migration does not mean all older rows can be interpreted as v2.")],
  "execution":"The agent creates a diagnosis with source citations. A tested, versioned calculator reproduces row contributions against approved definitions. Rules must be reviewed and implemented explicitly; arbitrary prose is not automatically safe executable policy.",
  "verify":"Check each row and the aggregate, rule status, customer scope and effective period. If source data is invalid or authoritative rules conflict, stop and request an owner decision.",
  "review":"Support and Reporting Engineering review the evidence. A separate approved action may create a repair PR or draft a customer explanation; the investigation itself does not close the ticket.",
  "metric":"Measure justified diagnosis rate, unsupported claims, engineer review time and avoidable handoffs on representative historical issues. Count failed and inconclusive attempts."},
 "export": {
  "intent":"Product asks engineering to add Northstar's monthly settlement export without changing other customers.",
  "queries":[("Git repository","Read export_csv, callers, sample row shape and baseline tests at the same commit used for both comparison runs."),("Jira","Fetch the implementation request and explicit approval links. Resolve which requirements are in scope for this release."),("Confluence","Fetch the customer export agreement, Finance's settlement/refund rules and the later draft. Verify approval and effective dates before using a rule.")],
  "join":[("Request: monthly settlement export","Agreement: America/New_York settlement date","Turn 'monthly' into a testable boundary rule; UTC October 1 can belong to September locally."),("Gross amount + fee fields in code","Finance rule: paid net differs from refund net","Generate separate acceptance tests for sale fees and nonrefundable refund fees."),("Existing exports and baseline tests","Jira scope: Northstar only; later document is draft","Isolate the new customer behavior and preserve legacy exports; do not implement the draft.")],
  "execution":"Assemble a requirement-to-source matrix and acceptance criteria first. An engineering agent edits an isolated branch/workspace and adds tests. Keep the same model, task and code baseline in both comparison conditions; only evidence access changes.",
  "verify":"Run existing tests plus independently reviewed acceptance tests for local month boundaries, daylight saving, statuses, refunds, currency, CSV escaping and customer isolation. Show the patch and failures as well as passes. Tests establish implemented behavior, not that the agreement was correctly approved.",
  "review":"A developer reviews the patch and test evidence; Product/Finance resolve ambiguous requirements. Open a draft PR only through an authorized action. Merge, deployment and sending customer exports are separate approval steps.",
  "metric":"Measure accepted requirements covered, first-review correctness, regression rate and total implementation-plus-review time. A plausible CSV or fast code generation alone does not establish efficiency."},
 "migration": {
  "intent":"An engineering owner asks whether shared ATLAS v1 support can be removed on October 15.",
  "queries":[("Git repository","Trace normalize callers, accepted schema versions, scheduled jobs, tests and deployment configuration at a known commit."),("Jira","Read migration scope, exclusions, blockers, ownership and linked approvals. A Done status is evidence of delivery only within that ticket's scope."),("Confluence + operations","Read the customer delivery agreement, replay/retention obligations and rollback runbook. Fetch fresh authorized per-job usage from the operational source; record its observation time.")],
  "join":[("Shared decoder feeds three jobs","Jira completion covers only daily_sales","Do not generalize one completed rollout to all consumers of the shared code."),("historical_replay reads v1","90-day archive obligation + conversion status","Deleting the decoder may break recovery even after live traffic reaches zero."),("partner_statement accepts v1","Cedar contract + dated traffic snapshot","Treat customer approval and current usage as separate release gates; refresh stale telemetry.")],
  "execution":"Build a dependency matrix: code consumer → customer/workflow → obligation → observed usage → accountable owner. Mark each relationship as confirmed, inferred or unknown and attach evidence. Missing results do not prove a dependency does not exist.",
  "verify":"Confirm repository coverage and runtime consumers, validate evidence freshness, test both schemas and rollback, and ask owners to validate critical dependencies. Do not turn an incomplete search into a claim that retirement is safe.",
  "review":"Engineering, Data Operations and customer owners approve their gates. Canary only a cleared workflow. Remove shared support only after every dependent is cleared and rollback/replay remain viable.",
  "metric":"Measure missed dependencies, unsupported go/no-go claims, owner review effort and rollout-plan acceptance against a human-validated dependency inventory. Do not use 'more blockers found' alone as success."}
}


def render(name):
 d=DEFINITIONS[name]; f=FLOWS[name]
 sources=' · '.join(f'<a href="/documents/{e(id)}">{e(id)}</a>' for id in d['sources'])
 query=''.join(f'<article><span class="eyebrow">{e(source)}</span><p>{e(text)}</p></article>' for source,text in f['queries'])
 joins=''.join(f'<tr><td>{e(a)}</td><td>{e(b)}</td><td>{e(c)}</td></tr>' for a,b,c in f['join'])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(d['title'])} · Production architecture</title><link rel="stylesheet" href="/portfolio.css"></head><body><header><a class="brand" href="/">data honey / context at work</a><nav><a href="/demos/{name}">Open demo {d['number']}</a><a href="/">All demos</a></nav></header><main><span class="eyebrow">WORKFLOW & ARCHITECTURE / DEMO {d['number']}</span><h1>{e(d['title'])}</h1><p class="lead">How this workflow would run against real company systems.</p><div class="notice"><b>Proposed production design.</b> This describes the intended integration, not infrastructure already deployed. The executable demos use synthetic local sources. Company permissions, connectors and business requirements must be validated before rollout.</div>
<section><h2>1. Start with the request and its scope</h2><p>{e(f['intent'])}</p><p>Attach the requesting user's identity, authorized project/customer, reporting or decision date, and repository revision. Establish what the user wants to know or change before searching.</p></section>
<section><h2>2. Pull evidence from the systems that own it</h2><div class="flow"><div>Request + user identity</div><b>→</b><div>Agent / tool router</div><b>→</b><div>Permission-checked connectors<br><small>MCP tools or direct service APIs</small></div></div><div class="grid three">{query}</div><p class="small">Open the synthetic source examples for this workflow: {sources}</p><p>Search narrows the candidates; then fetch complete relevant records and follow their approved links. The connector returns source URL/ID, body, version, owner, approval evidence, scope, effective dates and retrieval time. Document page status alone may not represent business approval; use the team's actual approval record.</p><details><summary>How retrieval works in production</summary><p>Query each source under the requesting user's permissions. Run independent searches concurrently, then retrieve the exact pages, issues, comments and code needed to resolve the question. Confluence pages supply requirements; Jira supplies decisions and their history; Git supplies implementation at a commit. The agent may issue follow-up searches when a dependency or disagreement appears.</p><p>A permission-aware search index can improve discovery at scale. It is optional: the whole repository need not be placed in a vector database. If an index is used, synchronize changes, deletions and access rules, then recheck permissions and retrieve current authoritative content before making a consequential recommendation.</p></details></section>
<section><h2>3. Combine evidence into explicit, checkable claims</h2><div class="flow"><div>Code + Jira + documents</div><b>→</b><div>Scoped evidence bundle<br><small>Full excerpts + provenance</small></div><b>→</b><div>Agent reasoning<br><small>Claims tied to sources</small></div></div><p>Combine by customer, product, version, date and linked decision—not merely matching keywords. Keep requested changes separate from approvals. Identify disagreements instead of letting the newest page automatically win.</p><div class="table-wrap"><table><thead><tr><th>First piece of evidence</th><th>What another system adds</th><th>Combined conclusion</th></tr></thead><tbody>{joins}</tbody></table></div><p class="small">Illustrative joins from this demo's synthetic scenario. In production every row needs a retrievable source citation and an explicit indication of uncertainty.</p></section>
<section><h2>4. Execute the workflow</h2><p>{e(f['execution'])}</p><h3>5. Verify independently</h3><p>{e(f['verify'])}</p><h3>6. Human review and controlled action</h3><p>{e(f['review'])}</p></section>
<section><h2>What is stored, and where?</h2><p><b>Systems of record:</b> source code stays in Git; issues stay in Jira; policies stay in Confluence or their document system. <b>Optional index:</b> approved searchable excerpts and metadata with access controls. <b>Run record:</b> the request, code revision, source versions, evidence used, tool events, outputs, checks and reviewer disposition in an access-controlled audit store with an agreed retention period.</p><p>Secrets remain in the connector credential store, not in prompts. Retrieved content is evidence, never authority to change the agent's instructions. Read access and write actions use separate permissions; unavailable or unauthorized evidence is an explicit limitation.</p></section>
<section><h2>How to establish whether it helps</h2><p>{e(f['metric'])}</p><p>Use matched tasks, the same model and tools where possible, counterbalanced order, and report every attempt. Include context preparation and maintenance costs. A context-rich answer can be more justified without being faster.</p></section>
<section><h2>Connector references</h2><p>This design is informed by the official interfaces; endpoint availability does not mean a connector is implemented here.</p><ul><li><a href="https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/">Jira Cloud issue search and permission requirements</a></li><li><a href="https://developer.atlassian.com/cloud/confluence/rest/v2/intro/">Confluence Cloud REST API v2</a> · <a href="https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-version/">page version retrieval</a></li><li><a href="https://github.com/modelcontextprotocol/modelcontextprotocol/blob/main/docs/specification/2025-06-18/basic/authorization.mdx">MCP transport authorization specification</a></li></ul></section><a class="button" href="/demos/{name}">Explore this demo →</a></main></body></html>'''
