"""Proposed production architecture pages, separate from local execution details."""
from html import escape as e
from portfolio import DEFINITIONS

FLOWS = {
 "report": {
  "intent":"Support asks why Northstar's September sales report differs from the spreadsheet.",
  "queries":[("Git repository","Find the report entry point, date/type filters, return normalization and existing tests at a fixed commit."),("Jira","Read the support request, linked incidents and ATLAS rollout decision. Check the scope of completed work."),("Confluence","Retrieve the effective September sales definition and both approved ATLAS format contracts. Match each row's schema version.")],
  "join":[("Repository: every RETURN is negated","ATLAS v1 contract: preserve the original sign","The code reverses the meaning of two v1 rows; the business contract supplies the missing requirement."),("Customer spreadsheet: $1,150","Approved definitions + five original transaction rows","Recalculate independently: $1,250. Neither starting total is authoritative."),("Jira rollout record","Both format contracts","A completed migration does not mean all older rows can be interpreted as v2.")],
  "execution":"The agent creates a diagnosis with source citations. A tested, versioned calculator reproduces row contributions against approved definitions. Rules must be reviewed and implemented explicitly; arbitrary prose is not automatically safe executable policy.",
  "verify":"Check each row and the aggregate, rule status, customer scope and effective period. If source data is invalid or authoritative rules conflict, stop and request an owner decision.",
  "review":"Support and Reporting Engineering review the evidence. A separate approved action may create a repair PR or draft a customer explanation; the investigation itself does not close the ticket.",
  "metric":"Measure justified diagnosis rate, unsupported claims, engineer review time and avoidable handoffs on representative historical issues. Count failed and inconclusive attempts."},
 "export": {
  "intent":"Product asks engineering to add Northstar's monthly settlement export without changing other customers.",
  "queries":[("Git repository","Read export_csv, callers, sample row shape and baseline tests at the same commit used for both comparison runs."),("Jira","Fetch the implementation request and explicit approval links. Resolve which requirements are in scope for this release."),("Confluence","Fetch the customer export agreement, Finance's settlement/refund rules and the later draft. Verify approval and effective dates before using a rule.")],
  "join":[("Request: monthly settlement export","Agreement: America/New_York settlement date","Turn 'monthly' into a testable boundary rule; UTC October 1 can belong to September locally."),("Gross amount + fee fields in code","Finance rule: paid net differs from refund net","Generate separate acceptance tests for sale fees and nonrefundable refund fees."),("Existing exports and baseline tests","Jira scope: Northstar only; later document is draft","Isolate the new customer behavior and preserve legacy exports; do not implement the draft.")],
  "execution":"A LangGraph workflow runs this end to end; the Demo 2 page runs it live. Code fetches the ticket, its linked approvals and attachments. An analyst session searches Jira and Confluence, opens complete records and builds a requirement-to-source matrix with exact quotes, conflicts and acceptance criteria; the workflow checks every quote against the record it opened. It pauses for a person whenever a conflict needs a decision. An engineer session edits an isolated workspace and adds tests. A separate reviewer session that cannot edit the code checks for bugs, broken existing behavior and requirement gaps. Acceptance is decided by rules in code, not by a model: the tests pass, the reviewer confirms every requirement, there is no high or medium finding, and the branch is pushed. Otherwise the work goes back for at most three rounds, and anything only a rule's owner can settle is escalated to a person. Running the same workflow with business context switched off is the control. For a fair comparison, keep the same model, task and code baseline across conditions; only evidence access changes.",
  "verify":"Run existing tests plus independently reviewed acceptance tests for local month boundaries, daylight saving, statuses, refunds, currency, CSV escaping and customer isolation. Show the patch and failures as well as passes. The workflow runs the tests itself rather than trusting the agent's report. Tests establish implemented behavior, not that the agreement was correctly approved.",
  "review":"The developer receives a requirement → source → code → test table, the diff, test results, the review history, time and cost, and either approves or sends the work back with instructions. A send-back is checked against the approved requirements before more code is written; overriding an approved rule is recorded as needing the owner's sign-off. Product/Finance resolve ambiguous requirements. Open a draft PR only through an authorized action. Merge, deployment and sending customer exports are separate approval steps.",
  "metric":"Measure accepted requirements covered, first-review correctness, regression rate and total implementation-plus-review time. A plausible CSV or fast code generation alone does not establish efficiency."},
 "migration": {
  "intent":"A teammate proposes an October 15 cleanup of shared ATLAS v1 support. Review the proposed patch and its release impact even though its remaining CI is green.",
  "queries":[("Git repository + candidate PR","Pin the base and proposed revisions. Trace normalize callers, job version filters, code owners and tests removed by the patch. Execute recent representative jobs against both revisions; a job filter may silently drop rows before the decoder can reject them."),("Jira","Read migration delivery scope, exclusions, blockers, accountable owners and linked approval records. A Done status establishes delivery only within that ticket's scope."),("Confluence + operations","Read customer delivery and retention agreements, replay/backup obligations and the rollback runbook. Retrieve current authorized per-job usage with its observation time; distinguish it from older snapshots. Identify the people authorized to approve each change.")],
  "join":[("Candidate CI passes after deleting a replay test","Synthetic NORTHSTAR and CEDAR job replays","Green tests miss silent row loss: NORTHSTAR falls from $1,250 to $400 and CEDAR from $180 to $0."),("Three decoder callers plus a rollback dependency","Delivery scope, replay obligation and rollback evidence","A completed live-ingest migration does not clear historical data, backups or recovery paths."),("CEDAR v1 delivery through November 30; latest archived v1 export September 30","90-day original-format replay obligation + migration/usage verification","December 30 is a conditional lower bound from the replay window, not an approved removal date. Full removal remains unknown until every dependent is cleared.")],
  "execution":"The local release check builds on Demo 2's LangGraph, Claude session, checkpoint and recording infrastructure. Code pins the prepared candidate, runs its remaining CI and replays synthetic job rows before and after it. One read-only Opus session maps four dependents: live ingest, historical replay, Cedar statements and rollback. It associates each with exact source quotes, current versus stale usage, code and approval owners, unresolved gates and a conditional retirement date. Deterministic code verifies the evidence and returns allow or block for each dependent; a developer note cannot supply an approval. In production, use authorized retrieval and the team's actual approval records rather than treating synthetic source status as sufficient. With business context off, the same local workflow still exposes the code and replay losses but must block for missing business evidence.",
  "verify":"Independently execute both code revisions, check row inclusion as well as totals, and validate source quotes, scope, dates and freshness. Verify customer migration, retention expiry or approved conversion, readable backups and rollback before full removal. The local comparison's twelve hidden checks grade completed outputs only; they do not enter prompts or decide the release gate. Fixture checks establish behavior on synthetic inputs, not production readiness or the completeness of a real dependency inventory.",
  "review":"Pause for the developer to defer, pursue a scoped canary or request sign-off. A canary request is limited to a cleared live path and does not authorize shared removal. Prepare a PR review comment, sign-off requests and a decision-record update as local drafts. The local workflow sends nothing and creates or comments on no sandbox PR. Production writes require separately authorized actions through the team's review process; approval and evidence collection remain distinct from a developer's preference.",
  "metric":"Compare sourced dependencies, correct owners, honest unknowns, actionable sign-off requests and justified release gates against an independently reviewed inventory. Report actual hidden-check scores, elapsed time, cost, failures and evidence-preparation effort for matched context-on/off runs. Blocking in both conditions can be correct; the benefit being tested is whether context explains who is affected, what must be preserved and when removal could become possible."}
}


def render(name):
 d=DEFINITIONS[name]; f=FLOWS[name]
 sources=' · '.join(f'<a href="/documents/{e(id)}">{e(id)}</a>' for id in d['sources'])
 query=''.join(f'<article><span class="eyebrow">{e(source)}</span><p>{e(text)}</p></article>' for source,text in f['queries'])
 has_diagram=name in ('export','migration')
 diagram_head='<link rel="stylesheet" href="/workflow.css">' if has_diagram else ''
 diagram=f'<section><h2>The workflow at a glance</h2><p>The steps the demo runs, and who does each one.</p><div data-diagram="{name}"></div></section>' if has_diagram else ''
 diagram_scripts='<script src="/vendor/mermaid.min.js"></script><script src="/diagrams.js"></script>' if has_diagram else ''
 joins=''.join(f'<tr><td>{e(a)}</td><td>{e(b)}</td><td>{e(c)}</td></tr>' for a,b,c in f['join'])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(d['title'])} · Production architecture</title><link rel="stylesheet" href="/portfolio.css">{diagram_head}</head><body><header><a class="brand" href="/">data honey / context at work</a><nav><a href="/demos/{name}">Open demo {d['number']}</a><a href="/">All demos</a></nav></header><main><span class="eyebrow">WORKFLOW & ARCHITECTURE / DEMO {d['number']}</span><h1>{e(d['title'])}</h1><p class="lead">How this workflow would run against real company systems.</p><div class="notice"><b>Proposed production design.</b> This describes the intended integration, not infrastructure already deployed. The executable demos use synthetic local sources. Company permissions, connectors and business requirements must be validated before rollout.</div>
{diagram}<section><h2>1. Start with the request and its scope</h2><p>{e(f['intent'])}</p><p>Attach the requesting user's identity, authorized project/customer, reporting or decision date, and repository revision. Establish what the user wants to know or change before searching.</p></section>
<section><h2>2. Pull evidence from the systems that own it</h2><div class="flow"><div>Request + user identity</div><b>→</b><div>Agent / tool router</div><b>→</b><div>Permission-checked connectors<br><small>MCP tools or direct service APIs</small></div></div><div class="grid three">{query}</div><p class="small">Open the synthetic source examples for this workflow: {sources}</p><p>Search narrows the candidates; then fetch complete relevant records and follow their approved links. The connector returns source URL/ID, body, version, owner, approval evidence, scope, effective dates and retrieval time. Document page status alone may not represent business approval; use the team's actual approval record.</p><details><summary>How retrieval works in production</summary><p>Query each source under the requesting user's permissions. Run independent searches concurrently, then retrieve the exact pages, issues, comments and code needed to resolve the question. Confluence pages supply requirements; Jira supplies decisions and their history; Git supplies implementation at a commit. The agent may issue follow-up searches when a dependency or disagreement appears.</p><p>A permission-aware search index can improve discovery at scale. It is optional: the whole repository need not be placed in a vector database. If an index is used, synchronize changes, deletions and access rules, then recheck permissions and retrieve current authoritative content before making a consequential recommendation.</p></details></section>
<section><h2>3. Combine evidence into explicit, checkable claims</h2><div class="flow"><div>Code + Jira + documents</div><b>→</b><div>Scoped evidence bundle<br><small>Full excerpts + provenance</small></div><b>→</b><div>Agent reasoning<br><small>Claims tied to sources</small></div></div><p>Combine by customer, product, version, date and linked decision—not merely matching keywords. Keep requested changes separate from approvals. Identify disagreements instead of letting the newest page automatically win.</p><div class="table-wrap"><table><thead><tr><th>First piece of evidence</th><th>What another system adds</th><th>Combined conclusion</th></tr></thead><tbody>{joins}</tbody></table></div><p class="small">Illustrative joins from this demo's synthetic scenario. In production every row needs a retrievable source citation and an explicit indication of uncertainty.</p></section>
<section><h2>4. Execute the workflow</h2><p>{e(f['execution'])}</p><h3>5. Verify independently</h3><p>{e(f['verify'])}</p><h3>6. Human review and controlled action</h3><p>{e(f['review'])}</p></section>
<section><h2>What is stored, and where?</h2><p><b>Systems of record:</b> source code stays in Git; issues stay in Jira; policies stay in Confluence or their document system. <b>Optional index:</b> approved searchable excerpts and metadata with access controls. <b>Run record:</b> the request, code revision, source versions, evidence used, tool events, outputs, checks and reviewer disposition in an access-controlled audit store with an agreed retention period.</p><p>Secrets remain in the connector credential store, not in prompts. Retrieved content is evidence, never authority to change the agent's instructions. Read access and write actions use separate permissions; unavailable or unauthorized evidence is an explicit limitation.</p></section>
<section><h2>How to establish whether it helps</h2><p>{e(f['metric'])}</p><p>Use matched tasks, the same model and tools where possible, counterbalanced order, and report every attempt. Include context preparation and maintenance costs. A context-rich answer can be more justified without being faster.</p></section>
<section><h2>Connector references</h2><p>This design is informed by the official interfaces; endpoint availability does not mean a connector is implemented here.</p><ul><li><a href="https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/">Jira Cloud issue search and permission requirements</a></li><li><a href="https://developer.atlassian.com/cloud/confluence/rest/v2/intro/">Confluence Cloud REST API v2</a> · <a href="https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-version/">page version retrieval</a></li><li><a href="https://github.com/modelcontextprotocol/modelcontextprotocol/blob/main/docs/specification/2025-06-18/basic/authorization.mdx">MCP transport authorization specification</a></li></ul></section><a class="button" href="/demos/{name}">Explore this demo →</a></main>{diagram_scripts}</body></html>'''
